### ISSUE TITLE
Unable to determine acceptable data type

### ISSUE THREAD

**Issue by ValeriyRCG** [AdrianStrugala/AvroConvert#102]
**What is the bug?**
I am trying to use the AvroConvertOnline tool to create classes from an avro schema provided by salesforce/a third party and it says it cannot process the provided schema.

**How to reproduce?**
Take the provided text file and try to run it through the AvroConvertOnlineTool. You should get an exception of 

> Exception:
Unable to determine acceptable data type for [ "null", "string", { "type": "record", "name": "Switchable_PersonName", "fields": [ { "name": "Salutation", "type": [ "null", "string" ], "default": null }, { "name": "FirstName", "type": [ "null", "string" ], "default": null }, { "name": "LastName", "type": [ "null", "string" ], "default": null }, { "name": "MiddleName", "type": [ "null", "string" ], "default": null }, { "name": "InformalName", "type": [ "null", "string" ], "default": null }, { "name": "Suffix", "type": [ "null", "string" ], "default": null } ] } ]

*What is the Avro schema?*
The avro schema in question can be found in the attached file. It is too big to paste into this comment.

*What is the Avro data? Fill up the section or provide a sample file*
The schema is too big to show everything here, but the main issue is the Name field of the schema. As is shown from the schema, it can be either a string, null, or a record type known as a SwitchablePersonName so it may look like this:
`{"name": "Some Account Name"}`
or
`{"name": {"firstName:"David", lastName: "Avro", middleName:"mid"....}`
Here is the schema segment that is causing the issue:
I noticed that it may be a little difficult to find the problem field so here is the exact field that is causing issues in the schema:
`{
      "name": "Name",
      "type": [
        "null",
        "string",
        {
          "type": "record",
          "name": "Switchable_PersonName",
          "fields": [
            {
              "name": "Salutation",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "FirstName",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "LastName",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "MiddleName",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "InformalName",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "Suffix",
              "type": [
                "null",
                "string"
              ],
              "default": null
            }
          ]
        }
      ],
      "doc": "Data:Switchable_PersonName",
      "default": null
    },`

**What is the expected behavior?**
The expected behaviour is to have concrete classes created that can deserialize incoming account messages while being able to use the field as both a string and as an object with its own properties.
[AccountSchema.txt](https://github.com/AdrianStrugala/AvroConvert/files/11175847/AccountSchema.txt)

**Comment by ValeriyRCG** [comment]
I noticed that it may be a little difficult to find the problem field so here is the exact field that is causing issues in the schema:
`{
      "name": "Name",
      "type": [
        "null",
        "string",
        {
          "type": "record",
          "name": "Switchable_PersonName",
          "fields": [
            {
              "name": "Salutation",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "FirstName",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "LastName",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "MiddleName",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "InformalName",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "Suffix",
              "type": [
                "null",
                "string"
              ],
              "default": null
            }
          ]
        }
      ],
      "doc": "Data:Switchable_PersonName",
      "default": null
    },`

**Comment by AdrianStrugala** [comment]
Thank you for reporting the problem. That's a new case, not supported at the moment. How do you create a C# model which contains a property that is a string and a class at the same time?

**Comment by Valeriyyy** [comment]
Hi the way I am handling this right now is by using apache avro to deserialize the avro payload into classes generated by the avrogen cli. The cli creates a class that has the Name property as an `object`. Once the payload is deserialized into a C# class, I check whether the property can be cast to the Switchable_PersonName type with `event.Name is Switchable_PersonName`. If it can be cast, I use separate code to treat it as a class, otherwise I use the ToString method to extract the string of the object.

**Comment by AdrianStrugala** [comment]
Hello @ValeriyRCG,

Thank you for your contribution. The properties of a few types are now correctly generated and defaulted to the object type.  This change is available from **v.3.3.6** of AvroConvert.

Regards,
Adrian
