### ISSUE TITLE
Error when serializing short value, cannot find match for int16

### ISSUE THREAD

**Issue by janny93** [AdrianStrugala/AvroConvert#109]
**What is the bug?**
Short values are not handled by the converter (is this supported?), as an error is produced when trying to serialize a model that contains the int16 short type.
![image](https://user-images.githubusercontent.com/124273385/236815644-c1b32046-46e7-4567-8d9a-bfc823452109.png)

**How to reproduce?**
```
public class SomeData
{
    public short ShortValue { get; set; }
    public short? ShortValueNullable { get; set; }
}

[Fact]
public void DemonstrateError()
{
    var model = new SomeData();
    model.ShortValue = 1;
    model.ShortValueNullable = 1;

    // Serialize
    var serializedModel = AvroConvert.Serialize(model);
}
```

*What is the Avro schema?*
Schema fetched with `AvroConvert.GenerateSchema(typeof(SomeData))`
```
{"name":"SomeData","namespace":"<redacted>","type":"record","fields":[{"name":"ShortValue","type":"int"},{"name":"ShortValueNullable","type":["null","int"]}]}
```

*What is the Avro data? Fill up the section or provide a sample file*
NA

**What is the expected behavior?**
Expects the converter to handle short types as well. Maybe needs to be mapped internally to int32 when serializing (and opposite when deserializing)?

**Comment by AdrianStrugala** [comment]
Hello,
Thank you for reporting the problem. It definitely is a bug, I will work on fix.
Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Hello @Fhyarnir @janny93,

Thank you for your contribution. Your fix is available from **v.3.3.5** of AvroConvert.

Regards,
Adrian
