### ISSUE TITLE
Add custom data converter support

### ISSUE THREAD

**Issue by apivkine** [AdrianStrugala/AvroConvert#114]
**Describe the solution you'd like**
I'm not sure if this is something that is already supported, however I believe it would be very valuable to add support for specifying custom converters to map unsupported .NET types to supported ones (i.e. similar to how Newtonsoft Json handles this [here](https://www.newtonsoft.com/json/help/html/JsonConverterAttributeProperty.htm) and [here](https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm)). 

For example, when dealing with memory-pooled data (i.e. System.Buffers.ArrayPool.Rent()), we do not know the length of the buffer - only that it is equal or greater than the requested size. Therefore, we cannot simply set the serializable object's property to the buffer, but we can do that if we can supply the length at runtime (i.e. by wrapping it in Memory<byte> or ReadOnlyMemory<byte>). 

If we create a new byte array and copy the data, we lose the benefits of using memory pooling, but if we were able to simply write the bytes from that memory into the output avro stream somehow (i.e. via AvroWriter of some kind

**Describe implementation idea**
Perhaps something like this could be implemented:

```
    [DataContract(Name = "Data", Namespace = "userspace")]
    public class DataObject
    {
        [DataMember(Name = "id")]
        public string Id { get; set; }

        [DataMember(Name = "data")]
        [CustomConverter(typeof(MemoryConverter))
        public Memory<byte> Data { get; set; }       
    }

    public class MemoryConverter : IPropertyConverter
    {
        // Implement OnSerialize/OnDeserialize mapping of .NET type to Avro-supported type
        // It will be necessary to provide access to the avro stream at this point and helper methods to read/write a property to this stream

        public bool OnSerialize(object value, IAvroWriter avroWriter)
        {
             if (value is Memory<byte> memoryValue)
             {
                  avroWriter.Write(memoryValue.Span);
                  return true;
             }

             return false;
        }

       // Something similar for OnDeserialize()
    }
```

**Additional context**
The ultimate goal is to accomplish the following:
- Allow custom conversion between a .NET data type and an Avro data type.
- Support a no-allocation approach (i.e. Span/Memory/Streams).

**Comment by AdrianStrugala** [comment]
Hello @apivkine @bkobel @shargon

Please take a look at the draft PR with custom converters: https://github.com/AdrianStrugala/AvroConvert/pull/117

The idea is pretty simple: you can now provide your converter:
```csharp 
   public interface IAvroConverter
    {
        public TypeSchema TypeSchema { get; }

        public void Serialize(object data, IWriter writer);

        object Deserialize(Type readType, IReader reader);
    }
```
The matching is done on runtime type (property of TypeSchema). I have included a test covering the new path: https://github.com/AdrianStrugala/AvroConvert/pull/117/files#diff-570bfd57263c5a604f990da30e8f6684319375691277ebd26e51af85430a63e9

Please let me know if it meets your expectations,
Adrian
