### ISSUE TITLE
Unable to cast object of type 'SolTechnology.Avro.Schema.RecordSchema' to type 'SolTechnology.Avro.Schema.ArraySchema'

### ISSUE THREAD

**Issue by OscarCanek** [AdrianStrugala/AvroConvert#12]
Sometimes I get the following error using the `AvroConvert.Deserialize`:

```
 System.InvalidCastException: Unable to cast object of type 'SolTechnology.Avro.Schema.RecordSchema' to type 'SolTechnology.Avro.Schema.ArraySchema'.
```

You know why this happened?

**Comment by AdrianStrugala** [comment]
Hi,
Could you please provide a code sample? It would help me with reproducing the issue.
In general, this exception is thrown when schema used for serialization contains List<T>, but schema used for deserialization contains not a collection, but only a single object of type T.

It may always be a bug, though :) With the code snippet I could investigate the problem more.

**Comment by AdrianStrugala** [comment]
closed due to lack of information
