### ISSUE TITLE
Avro2Json different output

### ISSUE THREAD

**Issue by AlbertoMonteiro** [AdrianStrugala/AvroConvert#126]
**Describe the solution you'd like**
Given this model
```csharp
public record Person(string Name, string? LastName);
```

When I do this
```csharp
var bytes = AvroConvert.Serialize(new Person("Alberto", "Xpto"));
Console.WriteLine(AvroConvert.Avro2Json(bytes));
```
I get
```json
{"Name":"Alberto","LastName":"Xpto"}
```

I am using GCP PubSub and it doesnt accept that json when I use GPC UI, I need this json to work

```json
{"Name":"Alberto","LastName": { "string": "Xpto" }}
```

**Describe implementation idea**
Is there any way using this lib to get this other json?

**Comment by AdrianStrugala** [comment]
Hello,
I have used some external tool to produce a C# model from the other json and it produced following model:

```csharp
    public class LastName
    {
        public string @string { get; set; }
    }

    public class Person
    {
        public string Name { get; set; }
        public LastName LastName { get; set; }
    }
```csharp 

So if you will create a record following this model, then you will get the desired json. It has nothing to do with Avro.

**Comment by AlbertoMonteiro** [comment]
Yeah, I knew that I can create other types to do this, actually it isn't a viable solution for my need.

Thanks for the attention!
