### ISSUE TITLE
Support get only properties 

### ISSUE THREAD

**Issue by Mitkee** [AdrianStrugala/AvroConvert#138]
**Describe the solution you'd like**
Currently, get only properties is not supported in deserialization. For example: 

```
public class MyThing {
  public int Number {get; set; }
  public int NextNumber => Number +1;
}
```
We can correctly write this schema, but we'll be unable to read it since NextNumber does not have a setter. As a workaround for this, the following can be done:

```
public class MyThing {
 public int Number {get; set;}
 public int NextNumber  {
        get => Number +1;
        init
        {
            //Ignored, set method only here to not make deserialization fail
        }
    }
}
``` 

It would be nice if get only properties would be ignored either out of the box, or if a special attribute could be added to opt in for this behavior. 

**Describe implementation idea**
How it could be done?
Either we make the following case work out of the box; 
```
public class MyThing {
  public int Number {get; set; }
  public int NextNumber => Number +1;
}
```
Or, a custom attribute is added to support this case: 
```
public class MyThing {
  public int Number {get; set; }
  [ReadOnly]
  public int NextNumber => Number +1;
}
```

The expected outcome of both options would be that the value is written when deserializing, but it won't be populated when deserializing.

**Comment by AdrianStrugala** [comment]
Hello!
Thank you for reporting this problem. I will investigate the solution.
Best,
Adrian

**Comment by AdrianStrugala** [comment]
Hello @Mitkee 

The fix is ready. From **v.3.4.2 of AvroConvert** the get-only properties should not be throwing errors during deserialization.

Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Well, I need to dig deeper into that

**Comment by AdrianStrugala** [comment]
Hey,

The problem was with caching during the deserialization of a collection of classes with read-only properties. It should be fixed now.
As for the calculated decimal property you might want to add AvroDecimal attribute:
```csharp
[AvroDecimal(Precision = 28, Scale = 28)]
public decimal? AveragePricePerWeight => Toys?.Average(t => t.PricePerWeightUnit);
```
It's to ensure the result not exceeding max precision of avro decimal.

Best,
Adrian
