### ISSUE TITLE
Deserializing from avro to json using Avro2Json only returns first row in list.

### ISSUE THREAD

**Issue by famattsson** [AdrianStrugala/AvroConvert#152]
An avro bytearray contains data in a list format. I have confirmed this by saving the bytearray to a file and using other tools to convert to json, in which case I get a list of values. 

**How to reproduce?**
Have an avro file with several rows of objects and call Avro2Json with that bytearray, then observe the results.

*What is the Avro data? Fill up the section or provide a sample file*
[avrofile.txt](https://github.com/AdrianStrugala/AvroConvert/files/14704302/avrofile.txt)

**What is the expected behavior?**
To get a json string like this
[avrojson.json](https://github.com/AdrianStrugala/AvroConvert/files/14704308/avrojson.json)

**Comment by AdrianStrugala** [comment]
Hey,
Thank you for reporting the bug. I will work on a fix.
Best,
Adrian

**Comment by AdrianStrugala** [comment]
Hello @famattsson 

Thank you for your contribution. The fix is available from **v.3.4.7** of AvroConvert.

Regards,
Adrian
