### ISSUE TITLE
SolTechnology.AvroConverter does not have a strong name

### ISSUE THREAD

**Issue by ItaiBolyasni25** [AdrianStrugala/AvroConvert#165]
**What is the bug?**
Cannot compile AvroConverter in my project because the dlls aren't signed. Would it be possible to sign the dll, i can help with the process if needed. 

Thank you for creating this package :)

error CS8002: Referenced assembly 'SolTechnology.Avro, Version=3.4.8.0, Culture=neutral, PublicKeyToken=null' does not have a strong name

**Comment by AdrianStrugala** [comment]
Hey @ItaiBolyasni25,
I am not familiar with signing dlls. Could you provide more info about it? And about your use case? I am wondering when it's required.
Best,
Adrian
