### ISSUE TITLE
Camel-case to pascal-case deserialization convention

### ISSUE THREAD

**Issue by thorhj** [AdrianStrugala/AvroConvert#17]
I have a simple object serialized with Avro using the following schema:

```json
{
  "type": "record",
  "name": "SourceObject",
  "namespace": "ConsoleApp18",
  "fields": [
  {
    "name": "name",
    "type": "string"
  },
  {
    "name": "age",
    "type": "int"
  },
  {
    "name": "enabled",
    "type": "boolean"
  }]
}
```

The field names are camel-cased, but in C# I want to use pascal-casing and deserialize into the following class:

```csharp
public class TargetObject
{
    public string Name { get; set; }
    public int Age { get; set; }
    public bool Enabled { get; set; }
}

...

var target = AvroConvert.Deserialize<TargetObject>(avroBytes);
```

When I do this, the properties all hold their default values because the fields are case-sensitive. One way around this is to use `DataMemberAttribute`, e.g.:

```csharp
[DataMember(Name = "name")]
public string Name { get; set; }
```

Since I know the fields are always in camel-case, and I always want them deserialized to pascal-case, it would be much easier if I could define that convention to take effect for all properties somehow. Is this possible?

**Comment by AdrianStrugala** [comment]
My proposition as a solution is to apply case insensitive matching between properties and the name of the fields in the schema.

In the result
`
public int Age { get; set; }
`
would be matched to either:
```json
 {
    "name": "age",
    "type": "int"
  },
```
or
```json
 {
    "name": "Age",
    "type": "int"
  },
```

 What is your opinion @thorhj ?

**Comment by AdrianStrugala** [comment]
I've implemented the changes - mapping now is case insensitive.
They are part of version 2.5.1
