### ISSUE TITLE
Deserializing a large .avro file with multiple blocks?

### ISSUE THREAD

**Issue by eyiu** [AdrianStrugala/AvroConvert#19]
I have a large .avro file that contains multiple blocks where each block contains many rows of data. When I try to deserialize the file with the following calls, the return array only contains the entries from the first block. The rest of blocks inside the .avro file are skipped. Is that the correct way to deserialize a large .avro file with AvroConvert?

    [DataContract(Name = "AvroRecord")]
    public class AvroRecord
    {
        [DataMember(Name = "message1")]
        public byte[] Message1;

        [DataMember(Name = "message2")]
        public byte[] Message2;
    }
`byte[] avroData = File.ReadAllBytes(avroFilePath);`
`AvroRecord[] records = AvroConvert.Deserialize<AvroRecord[]>(avroData);`

**Comment by AdrianStrugala** [comment]
In fact, your data is collection of collection of AvroRecord.
Please try to invoke:
`
List<AvroRecord[]> records = AvroConvert.Deserialize<List<AvroRecord[]>>
`
Did it read all the data? 

I'm working now on improvement of reading huge Avro files. Should be more intuitive soon
