### ISSUE TITLE
Nullable DateTime Error

### ISSUE THREAD

**Issue by youare** [AdrianStrugala/AvroConvert#21]
I have a simple example which will throw 
SolTechnology.Avro.Exceptions.AvroException: 'Cannot find a match for System.DateTime in {"type":["null","long"]}'

The reason is because I am trying to serialize an object with a value in DateTime? field.

        public class NullableDateTimeTest
        {
            public DateTime? DateTime { get; set; }
        }
        public static async Task Main(string[] args)
        {
            var myTest = new NullableDateTimeTest { DateTime = DateTime.Now };
            var schema = AvroConvert.GenerateSchema(myTest.GetType());
            var serializeHeadless = AvroConvert.SerializeHeadless(myTest, schema);
            var deserializeHeadless = AvroConvert.DeserializeHeadless<TestEvent>(serializeHeadless, schema);
       }

**Comment by AdrianStrugala** [comment]
Hi,
Thank you for reporting the bug (your right, resolving DateTime? throws an exception). 
I'll take care for this soon

**Comment by AdrianStrugala** [comment]
The fix is ready in AvroConvert 2.6.1

Thanks for opening the issue!
