### ISSUE TITLE
avro.codec header

### ISSUE THREAD

**Issue by marekchud** [AdrianStrugala/AvroConvert#22]
Hi Adrian,

When there is no codec designated it looks like the library fails out.

I downloaded the source and changed :

`SolTechnology.Avro.AvroToJson.Encoder.Decode`

From:
`var codec = AbstractCodec.CreateCodecFromString( GetMetaString(header.MetaData[DataFileConstants.CodecMetadataKey]));`

To:
 
`var codec = !header.MetaData.ContainsKey(DataFileConstants.CodecMetadataKey) ? new NullCodec() :  AbstractCodec.CreateCodecFromString( GetMetaString(header.MetaData[DataFileConstants.CodecMetadataKey]));`

This seems to have worked. Disclaimer - I only just started with avro so this is all new to me and perhaps I'm using it wrong to begin with!

Thanks,
Marek

**Comment by AdrianStrugala** [comment]
Hi Marek,

Thank you for your catch!
It was a bug, I've solved it in a little bit different way.

You can find the fix in version 2.6.2

Have a nice day!
Adrian

**Comment by marekchud** [comment]
Hi Adrian,

No problem. I should have actually mentioned that that was not the only placed required to make the change.

Do a search on `AbstractCodec.CreateCodecFromString` and you will find that it needs to be updated in more than 1 place. I just used the latest package and still failed out on a missing avro.codec header message. I am using `AvroConvert.Deserialise<T>(byte[]) ` . Presumably also, when there is a missing codec header you now return a `NullCodec()` rather than throw an exception?

Thanks again,

Marek

**Comment by AdrianStrugala** [comment]
Hi Marek,

Yeah, I thought I fixed it in a layer below. The idea was to return NullCodec as the default value.
Reopening the issue, I will take a careful look at this.

Thanks,
Adrian

**Comment by AdrianStrugala** [comment]
Hi Marek,

After closer investigation - the issue was caused by two restrictions. One of them was solved previously, but the full fix is done in version 2.6.3.
Could you please confirm if the decoding works as expected?

Thanks,
Adrian
