### ISSUE TITLE
How can we convert reflected type instead of concrete type and convert to json

### ISSUE THREAD

**Issue by bhatrohit85** [AdrianStrugala/AvroConvert#30]
I have scenario where i will dynamically create class using reflection using schema json and then want to consume  from a kafka topic expecting that reflected class. If i use ISpecificRecord in consumer builder and avrodeserializer , it throws error in consume method i.e value deserialization error . Else , if i want to consume Generic Record ,that gets consumed but then Avroconvert only supports concrete type using reflection. 

Please help me how can i send reflected type in consumer , else how can is use genericrecord with avroconvert.

[github-avroconvert.zip](https://github.com/AdrianStrugala/AvroConvert/files/6021576/github-avroconvert.zip)

**Comment by AdrianStrugala** [comment]
Hi,

I don't know if I correctly understand your question, but taking look at the code it seems that there is some issue:
1) In Kafka Producer the data should be serialized (I suppose to Avro format in the case)
2) In Kafka Consumer you should **deserialize** incoming data as it is already in Avro format
3) You can automatically convert it to JSON by using AvroConvert.Avro2Json feature (as alternative to deserialization)

Answering the last question, you can send schema of reflected type using AvroConvert.Serialize - the result contains schema and data itself.

I don't know if it answers your question, if not please provide more details.

**Comment by bhatrohit85** [comment]
Hi Adrian ,

I am stuck with consumer part. With every schema , you require a class that is available inside my project where i write the consumer.But as a generic solution , we can not use it like that way , thus , i am generating the class from schema json using reflection. 

Q 1. How to  consume data of reflection object using Kafka Consumer in .net ?

Q2. Currently , i can consume data using GenericRecord type instead of Reflection object but there is there a way to convert GenericRecord type message value to json inside AvroConvert ?

I have attached the cs file for consumer , here i have created class using reflection and implemented consumer code.
Now , how can i write consumer using reflected object or how to use genericrecord type to convert to json.

[Form1.zip](https://github.com/AdrianStrugala/AvroConvert/files/6034116/Form1.zip)

**Comment by AdrianStrugala** [comment]
OK, got it.

1) How do you provide a reflection class? Is it Type or Dynamic object? Or maybe in another way?
2) What do you expect as a result of reflection deserialization?
3) GenericRecords wouldn't be supported by AvroConvert. But if you have GenericRecord model, why cannot you create the concrete model?

**Comment by bhatrohit85** [comment]
Hi Adrian,

As per my understanding , kafka consumer takes Either Avro.GenericRecord Class or any class implementing Avro.ISpecificRecord Interface.
Scenario 1:
When i use genericrecord and specify that to build consumer like
using (var schemaRegistry = new CachedSchemaRegistryClient(new SchemaRegistryConfig { Url = "localhost:8081" }))
using (var consumer =
                    new ConsumerBuilder<Null, GenericRecord>(new ConsumerConfig(conf))
                        .SetValueDeserializer(new AvroDeserializer<GenericRecord>(schemaRegistry).AsSyncOverAsync())
                        .Build())
{
consumer.Subscribe("topic1");
try
{
                              var consumeResult = consumer.Consume(cts.Token);
                              var value = consumeResult.Message.Value;
                              var byteData = AvroConvert.SerializeHeadless(value, schema);
                              var jsonData = AvroConvert.Avro2Json(byteData, schema);
}
catch{
throw;}

}
Now , i have value of type GenericRecord and this cannot be converted to json using avroconvert.

Scenario 2 : As specified , we will only have schema json of relevant topic and want to consume avro data for multiple clients 
and thus can not generate cs file for all the schemas and add them as a reference again in the code . This way , we will have to keep changing our code and that will not be a generic solution. Thus , we can generate class file for schema using reflection for which we do not need to change code. we will fetch schema from configuration which can be registered from UI form.

Now how to use this in consumerBuilder because if i write code like this , consumer throws error : Value Serialization error.

using (var schemaRegistry = new CachedSchemaRegistryClient(new SchemaRegistryConfig { Url = "localhost:8081" }))
                using (var consumer =
                    new ConsumerBuilder<Null, ISpecificRecord>(new ConsumerConfig(conf))
                        .SetValueDeserializer(new AvroDeserializer<ISpecificRecord>(schemaRegistry).AsSyncOverAsync())
                        .Build())
{
consumer.Subscribe("topic1");
try
{
                                var consumeResult = consumer.Consume(cts.Token);
                                var value = consumeResult.Message.Value;


                                var byteData = AvroConvert.SerializeHeadless(value, schema);
                                var jsonData = AvroConvert.Avro2Json(byteData, schema);
}
catch{
throw;}
}
So , instead of ISpecificRecord , how can i use the generated class instance to consume message and then convert the value read
from consume method to convert to json.

**Comment by AdrianStrugala** [comment]
Scenario 1:

AvroConsumer could take any model, it's totally up to you and not depended on Avro serializer implementation.
You are invoking SetValueDeserialize, which should handle all the deserialization. At this point you have Avro data and can manipulate it. Take a look at [this example](https://github.com/AdrianStrugala/AvroConvert/blob/master/src/Soltechnology.Avro.Kafka/Deserialization/AvroConvertDeserializer.cs) for reference.


Scenario 2:

You have have a type created in runtime, you could use this interface for deserialization:
dynamic Deserialize(byte[] avroBytes, Type targetType)

Hope it helps

**Comment by bhatrohit85** [comment]
Hi Adrian ,

1. SetValueDeserialize method does work and i get the value as GenericRecord Type but that will not work with AvroConvert.Avro2Json method.
2. If i specify SetValueDeserialize(new AvroDeserializer<ISpecificRecord>(registryconfig) , this does not deserialize and throws error : value deserialization error , however , i am producing the class on rumtime and setting values and then sending it like
runtimeClassObj as ISpecificRecord and it goes through to kafka topic and same can be read as genericrecord.

3. As specified by you , i should use dynamic Deserialize(byte[] avroBytes, Type targetType) method but how to get the avrobytes 
 is my question. If i specify ISpecificRecord type , i am unable to consume the message , if i specify GenericRecord , i can consume the message but then how to get avrobytes from that and deserialize that to targetType which is runtime Type.

I appreciate your help , hope you may guide me more on this.

**Comment by AdrianStrugala** [comment]
If you want to achieve your results you have to follow the steps:
1. Create custom IDeserializers as in given example
2. For scenario 1: Avro2Json can be used directly in first new Deserializer
3. For scenario 2: Deserialize(byte[] avroBytes, Type targetType) can be used directly in second new Deserializer.

That's it
