### ISSUE TITLE
Support doc

### ISSUE THREAD

**Issue by newbe36524** [AdrianStrugala/AvroConvert#32]
What about this:

```cs
    [Description("Doc of ProductInfo")]
    public record ProductInfo
    {
        [Description("Doc of productId")]
        public int ProductId { get; set; }
    }
```

into:

```json
{
    "type": "record",
    "name": "ProductInfo",
    "doc": "Doc of ProductInfo",
    "namespace": "Test",
    "fields": [{
        "name": "ProductId",
         "doc": "Doc of productId",
         "type": "int"
    }]
}
```

You know, doc is supported by avro:

https://avro.apache.org/docs/current/spec.html

**Comment by AdrianStrugala** [comment]
Hello,

Thanks for the idea. I've added it to our roadmap.

"Doc" attribute will be supported in:
- record
- record field
- enum
Do you think, there is any more suitable type?

Regards,
Adrian

**Comment by newbe36524** [comment]
I think it is enough, actually that is all possible locations shown in spec docs.

**Comment by AdrianStrugala** [comment]
Hi,

The Doc property is now supported. Usage is as you suggested, with the [Description] attribute.
You can find it in v.3.0.0 of the package.

Regards,
Adrian
