### ISSUE TITLE
Deserialization fails for field type array<T>

### ISSUE THREAD

**Issue by pmatpadi** [AdrianStrugala/AvroConvert#34]
Hello,
I noticed this library has issue with deserializing array type field. 
I use the AvroConvert.SerializeHeadless and AvroConvert.DeserializeHeadless APIs.
Here is the IDL file.  
```
@namespace("xyz")
protocol SendEmail {
  enum EmailBodyType {
    HTML, TEXT
  }

  enum Encoding {
    UTF8, UTF7, UTF32, ASCII 
  }

record EmailBody {
    EmailBodyType contentType;
    string messageBody;
    Encoding contentEncoding;
  }

/* Represents an Email Message detail. */
  record EmailMessage {
    array<EmailRecipient> from;
    /* sender might differ from the from list above if email is to be sent on behalf of someone else */
    EmailRecipient sender;
    array<EmailRecipient> to;
    string subject;
    EmailBody emailBody; 
}
}
```
Serialization works well, but deserialization fails with
```
Error Message:
   SolTechnology.Avro.Exceptions.AvroTypeMismatchException : Unable to deserialize [SendEmail] of schema [Record] to the target type [blackline.eventbus.notification.SendEmail]
---- SolTechnology.Avro.Exceptions.AvroTypeMismatchException : Unable to deserialize [EmailMessage] of schema [Record] to the target type [blackline.eventbus.notification.EmailMessage]
-------- SolTechnology.Avro.Exceptions.AvroTypeMismatchException : Unable to deserialize [array] of schema [Array] to the target type [System.Collections.Generic.IList`1[blackline.eventbus.notification.EmailRecipient]]
------------ System.NullReferenceException : Object reference not set to an instance of an object.
```
Thanks in advance for looking into this.
Priya

**Comment by AdrianStrugala** [comment]
Hello,

Thanks for reporting the problem. I'm starting the investigation, but have few questions.
1. Did you try the serialize/deserialize option (not the headless one)? Did it worked?
2. How the project is configured to include IDL files? Could you maybe provide fragments of the source code or link to github project?

**Comment by pmatpadi** [comment]
Hi,
Thanks for looking into this.
I did not have much luck using the non-headless serialize/deserialize methods. I got serialization error:
```
Error Message:
   System.Runtime.Serialization.SerializationException : Could not find any matching known type for 'Avro.Schema'.
```
In my project, we create IDL (.avdl) files, then convert them to .avsc using idl2schemata option as follows:
```
   java -jar $Env:AVRO_HOME/avro-tools-$AVRO_TOOLS_VERSION.jar idl2schemata $SRC_PATH/$folder/$file $DEST_PATH/$folder
```
and then generate dotnet bindings using avrogen nuget
https://www.nuget.org/packages/Confluent.Apache.Avro.AvroGen/

I have had success ser/deser objects  with schemas that do not include array types and non-optional enum types using AvroConvert.
I already provided the fragments from the IDL file which should help you to reproduce the issue. Currently my project is not open source to share link to github project. Please let me know if I can provide more info.

**Comment by AdrianStrugala** [comment]
I still don't understand how the project is set up. AvroConvert is a C# .NET library, do you use a .NET project and .cs files?
I can't reproduce the issue without this knowledge. Maybe you could share csproj configuration?

**Comment by pmatpadi** [comment]
Yes, we use .NET project and .cs files
.cs file is created using avrogen.
Here is the contents of csproj file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="31.0.3" />
    <PackageReference Include="AvroConvert" Version="2.7.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="coverlet.collector" Version="1.0.1" />
    
    <PackageReference Include="XunitXml.TestLogger" Version="2.1.26" />
  </ItemGroup>

    <ItemGroup>
    <ProjectReference Include="..\..\src\main\dotnet\EventBus.Schemas.csproj" />
  </ItemGroup>

</Project>
```
Does this help?

**Comment by AdrianStrugala** [comment]
Ok, I understand it now. The last piece of information that I miss is .NET model. Could you provide content of .cs files used for deserialization?

**Comment by pmatpadi** [comment]
Dotnet bindings: [xyz.zip](https://github.com/AdrianStrugala/AvroConvert/files/6246619/xyz.zip)
avsc format files [avroconvert.zip](https://github.com/AdrianStrugala/AvroConvert/files/6246620/avroconvert.zip)
Unit test [Archive.zip](https://github.com/AdrianStrugala/AvroConvert/files/6246631/Archive.zip)

**Comment by AdrianStrugala** [comment]
Ok, now I got the full picture now.
The problem with parsing enums is resolved, but the more important is:

**AvroConvert doesn't support Apache.Avro ISpecificRecord models**

Apache.Avro adds a lot of framework-specific items to its model. If you want to use AvroConvert properly change your models to pure C#. For example:

`	
    public class EmailMessage
    {
        public string Subject { get; set; }
        public List<EmailBody> EmailBody { get; set; }
        public MessageImportance? MessageImportance { get; set; }
    }
`

**Comment by pmatpadi** [comment]
Thanks Adrian. I appreciate you looking into solving the reported problems. 
These dotnet bindings are generated by https://www.nuget.org/packages/Apache.Avro/ from avdl files. 
Currently I don't see any option to use pure c# models. 

Just FYI, I found additional issues with Fixed and Map data types as well
FWIW, here are the errors:

```
SolTechnology.Avro.Exceptions.AvroTypeMismatchException : Unable to deserialize [map] of schema [Map] to the target type [System.Collections.Generic.IDictionary`2[System.String,System.String]]`
```

```
SolTechnology.Avro.Exceptions.AvroTypeMismatchException : [GenericFixed] required to write against [Fixed] schema but found sample_app.MD5
```
where
```
fixed MD5(256);
record Employee {
        map<int> skillsLevel;
        MD5 publicKey;
}
```

**Comment by AdrianStrugala** [comment]
To be more precise: AvroConvert does not support any Apache.Avro model.
AvroConvert requires compatible models to work with (you can see examples in the documentation)
