### ISSUE TITLE
"merge"?

### ISSUE THREAD

**Issue by ErikAndreas** [AdrianStrugala/AvroConvert#37]
Hi

I have a use-case where I have several items already in avro format (avro bc of transfer) and need to output all of them to one file, is there some sort of "merge" feat avail so that I don't have to deser/ser again?

```
foreach(var o in data) // list of avro encoded items
{
    var ed = AvroConvert.Deserialize<MyData>(o.Avrodata);
    objs.Add(ed);
}
using (var ms = new MemoryStream(AvroConvert.Serialize(objs))) 
{
    await cloudBlockBlob.UploadFromStreamAsync(ms);
}
```
is there a more effecient way of doing the above?

**Comment by AdrianStrugala** [comment]
Hi,

There is no such possibility at the moment, but I will investigate this as the next possible feature.

Thanks for the idea

**Comment by ErikAndreas** [comment]
You're welcome ; )

Guessing(!) most bits and pieces already are in there?! 
```
byte[] SerializeMergeAvroItems(IEnumerable<byte[]> avroItems)
// get schema from first item
// iterate items
  // encode but skip stuff already done? - too little knowledge of avro format here... 
```
would be a nice addition to an already great lib! thanks!

**Comment by AdrianStrugala** [comment]
Yeah, you are more or less right :)

How I see this:
```
byte[] MergeAvroObjects(IEnumerable<byte[]> avroObjects)
1) get schema from first item
2) iterate items - validate against the schema
3) and now the hard part starts. The library has to encode existing items as an collection of the items. 
-> Which implies change of schema ( <T> vs. IEnumerable<T>)

Could be like:
a) encode header with a schema for IEnumerable<T>
b) encode array start
c) copy and paste the data for each item
d) encode array end
```
I have to try out the possibilities. If you want to dig more into the topic, feel welcome :)

**Comment by AdrianStrugala** [comment]
Hello,

I've introduced the 'Merge' feature to AvroConvert. You can find it in version 3.1.0.

Thanks for the idea!
Adrian
