### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by Kipetcoff** [AdrianStrugala/AvroConvert#38]
We faced with a problem in conversion from avra to json.
Error "Arithmetic operation resulted in an overflow" during conversion 
[avro.txt](https://github.com/AdrianStrugala/AvroConvert/files/6443839/avro.txt)

Schema is

`{
                "type":"record",
                "name":"DepartmentAVRO",
                "namespace":"models.mvp.Department",
                "fields":[
                    {"name":"struct_code","type":"int","doc":"Идентификатор подразделения"},
                    {"name":"firm_id","type":"int","doc":"Идентификатор организации"},
                    { "name":"struct_parent","type":["int","null"],"doc":"Идентификатор родительского подразделения"},
                    { "name":"struct_name","type":"string","doc":"Наименование подразделения"},
                    { "name":"financial_short_name","type":"string","doc":"Код ЦФО"},
                    { "name":"start_date","type":["null", { "type": "long", "logicalType":"date"}],"doc":"Дата начала действия"},
                    { "name":"end_date","type":["null", { "type": "long", "logicalType":"date"}],"doc":"Дата окончания действия"}
                ]}`

Loooks it's here, in the code. This value is less than zero during reading value **financial_short_name**.
It should be "financial_short_name":"E131001"
![2021-05-07_22-18-41](https://user-images.githubusercontent.com/28597113/117498670-c7f0fa00-af82-11eb-9065-5758076cdd67.png)

**Comment by AdrianStrugala** [comment]
Thanks for reporting the bug.
I will take a look at this. Is the file serialized in regular way, or did you use headless option or one of the codecs?

**Comment by Kipetcoff** [comment]
Which file you mean? avro.txt? I saved bytes to file. I don't know is it correct or not. 
![2021-05-08_08-25-19](https://user-images.githubusercontent.com/28597113/117527792-48414a80-afd7-11eb-9269-3d3dfb5ec83a.png)

**Comment by AdrianStrugala** [comment]
I was able to reproduce the issue. To resolve it I have to know:
- how the avro object was created on producer side
- what are the values of the object properties
-what was the model that you used for deserialization

**Comment by Kipetcoff** [comment]
Hello,

- I don't know, because we only recieve velues from kafka. I can ask somebody, but it will take several days.
- `{
   "Schema":{
      "Tag":8,
      "Name":"DepartmentAVRO"
   },
   "struct_code":1057,
   "firm_id":4,
   "struct_parent":931,
   "struct_name":"Отдел обеспечения качества данных",
   "financial_short_name":"E131001",
   "start_date":633426048000000000,
   "end_date":637500672000000000
}`

- Schema is in the first post

By the way, int length was -34042907, may be this can help you.

**Comment by AdrianStrugala** [comment]
Hello,

I was not able to properly deserialize the avro.txt file that you attached. It didn't contain an Avro header and deserializing using the Headless option also didn't bring any meaningful results.

To proceed next with the investigation I need to know **exactly** how the file was produced (how the data was serialized to avro format).

**Comment by Kipetcoff** [comment]
Hello, 
Here is how it looks like from sender side.
`
public async Task<DeliveryResult<Null, T>> SendDataToKafkaAsync<T>(T row, string topicName, CancellationToken cancellationToken) where T : class, new()
        {
            ProducerBuilder<Null, T> producerInstance = new ProducerBuilder<Null, T>(_settings.ProducerConfig);

            using (var schemaRegistery = new CachedSchemaRegistryClient(_settings.SchemaRegisterConfig))
            using (var producer = producerInstance
                .SetValueSerializer(new AvroSerializer<T>(schemaRegistery, _settings.AvroSerializerConfig))
                .SetErrorHandler((produce, error) =>
                {
                    if (error.IsError)
                    {
                        _logger.LogError($"Delivery failed: {error.Reason}");
                    }
                }).Build())
            {
                try
                {
                    return await producer.ProduceAsync(topicName, new Message<Null, T> { Value = row });
                }
                catch (ProduceException<string, T> exp)
                {
                    _logger.LogError($"Error to produce in bus20 error message: {exp.Error.Reason}");
                    throw exp;
                }
                catch (Exception exp)
                {
                    _logger.LogError($"Error: {exp.Message}");
                    throw exp;
                }
            }
            
        }
`

**Comment by Kipetcoff** [comment]
Sorry, the code was changed recently, here is new version

`public async Task<DeliveryResult<Null, byte[]>> SendRecordsInBUSAsync<T>(T data, string topicName, string schema, ITraceContext traceContext, CancellationToken cancellationToken) where T : class, new()
        {
            _logger.LogInformation($"Try to send data in kafka");
            string strJsonSchema = schema;
            if(string.IsNullOrWhiteSpace(strJsonSchema))
            {
                strJsonSchema = AvroConvert.GenerateSchema(typeof(T));
            }

            //var converterData = AvroConvert.Serialize(data);
            var converterData = AvroConvert.SerializeHeadless(data, strJsonSchema);

            ProducerBuilder<Null, byte[]> producerInstance = new ProducerBuilder<Null, byte[]>(_settings.ProducerConfig);
            Headers headers = new Headers();
            if (traceContext != null)
            {
                headers.Add("TraceId", BitConverter.GetBytes(traceContext.TraceId));
                headers.Add("SpanId", BitConverter.GetBytes(traceContext.SpanId));
                long parenSpanId = traceContext?.ParentSpanId == null ? traceContext.SpanId : (long)traceContext.ParentSpanId;
                headers.Add("ParentSpanId", BitConverter.GetBytes(parenSpanId));
            }

            using (var schemaRegistery = new CachedSchemaRegistryClient(_settings.SchemaRegisterConfig))
            using (var producer = producerInstance
                //.SetValueSerializer(new AvroSerializer<GenericRecord>(schemaRegistery, _settings.AvroSerializerConfig))
                .SetErrorHandler((produce, error) =>
                {
                    if (error.IsError)
                    {
                        _logger.LogError($"Delivery failed: {error.Reason}");
                    }
                }).Build())
            {
                try
                {
                    return await producer.ProduceAsync(topicName, new Message<Null, byte[]> { Value = converterData, Headers = headers });
                }
                catch (ProduceException<string, T> exp)
                {
                    _logger.LogError($"Error to produce in bus20 error message: {exp.Error.Reason}");
                    throw exp;
                }
                catch (Exception exp)
                {
                    _logger.LogError($"Error: {exp.Message}");
                    throw exp;
                }
            }

        }`

**Comment by AdrianStrugala** [comment]
Hello,

 I was able to resolve the issue. You can find a test for it [here](https://github.com/AdrianStrugala/AvroConvert/blob/issue-38/tests/AvroConvertTests/Issue38Test.cs)
 
You are not following the Confluent Kafka messaging convention and I strongly advise you to use [Soltechnology.Avro.Kafka](https://www.nuget.org/packages/SolTechnology.Avro.Kafka/) NuGet package for Kafka communication or implement message deserializer similar to [this](https://github.com/AdrianStrugala/AvroConvert/blob/master/src/Soltechnology.Avro.Kafka/Deserialization/AvroConvertSchemaRegistryDeserializer.cs) one.

The problem itself was caused by a lack of the code:
```
              //Confluent Kafka format:
                //https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#wire-format
                if (stream.ReadByte() != 0x00)
                {
                    throw new InvalidDataException("Invalid Confluent Kafka data format");
                }
                var bytes = new byte[4];
                stream.Read(bytes, 0, bytes.Length);

                var id = BitConverter.ToInt32(bytes, 0);
```

There is still a problem with the data itself, because 633426048000000000 cannot be a valid value for avro 'date' type: [documentation](https://avro.apache.org/docs/current/spec.html).
But if you are using AvroConvert now also for serialization, everything should be working 👍

**Comment by Kipetcoff** [comment]
Hello,
Yes, they changed sender code and we changed consumer. Now we use AvroConvert to generate schema from the same model on the both sides
 var _schema = AvroConvert.GenerateSchema(typeof(T))
Then deserialize(serialize) with this schema
var value = AvroConvert.DeserializeHeadless<T>(_bytes, _schema);

Everything wokrs well now,thank you!
