### ISSUE TITLE
System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

### ISSUE THREAD

**Issue by khoshbin** [AdrianStrugala/AvroConvert#4]
Hi 

This is my test case:
    public class **Student**
    {
        public Guid Id { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public bool IsActive { get; set; }
        public Int32 Age { get; set; }
        public DateTime Created { get; set; }
        public List<Book> Books { get; set; } = new List<Book>();

    }
    public class **Book**
    {
        public Guid Id { get; set; }
        public String Topic { get; set; }
        public Decimal Price { get; set; }
    }

public void main(){
            Student theStudent = new Student();
            theStudent.Id = Guid.NewGuid();
            theStudent.FirstName = "His First Name";
            theStudent.LastName = "His Last Name";
           theStudent.Created = System.DateTime.Now;
            byte[] theResult = AvroConvert.AvroConvert.Serialize(theStudent);
            var theStudent2 = AvroConvert.AvroConvert.**Deserialize**<Student>(theResult);

}

But I encountered this exception in last line when deserializing:
System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

**Comment by AdrianStrugala** [comment]
Hi,

Thanks for reporting the bug. The fix is ready and it's being deployed.
Please check out the 1.8.1 version

Regards,
Adrian
