### ISSUE TITLE
Problem when serializing classes with inheritance

### ISSUE THREAD

**Issue by brunneus** [AdrianStrugala/AvroConvert#48]
Greetings!

I have the following class:

```
public class Course : KafkaMessage
{
    public Course()
    {
        CreatedAt = DateTime.UtcNow;
        Identifier = Guid.NewGuid();
    }

    public string Id { get; set; }
    public string Name { get; set; }
    public DateTime CreatedAt { get; set; }
}
```

The KafkaMessage inherit from Message which has a property `Identifier`.

When trying to serialize this class, the following occurs:

![image](https://user-images.githubusercontent.com/7253244/130816381-237b15a8-b71e-404d-b628-7589a3386d3e.png)

I downloaded the source code and I notice something "weird":

![image](https://user-images.githubusercontent.com/7253244/130816653-d57570e3-394d-4636-b25b-5951178a3ed9.png)

The `membersToSerialize` property has 3 times the property identifier. Since the `allMembers` property has only one reference to that particular property, the error occurs.

If I add the flag `BindingFlags.DeclaredOnly` to the `membersToSerialize` everything works fine.

This is the correct behaviour? Thanks in advance.

**Comment by AdrianStrugala** [comment]
Hello,

The bug is resolved. The fix is ready in 3.1.5 version of AvroConvert 

Thanks,
Adrian
