### ISSUE TITLE
Exception: 'An item with the same key has already been added. Key: 45523402'

### ISSUE THREAD

**Issue by asaridakis** [AdrianStrugala/AvroConvert#53]
Hello,

I am getting the error 'An item with the same key has already been added. Key: 45523402' when I am trying to Serialize an Object using multiple Threads. It seems that the Dictionary (private readonly Dictionary<int, Func<object, string, object>> gettersDictionary) in the Record Class, is not a 'ConcurrentDictionary'.

Here is the Test Function:

   [Fact]
        public void Serialize_VeryComplexClass_NoExceptionIsThrown_MultiThreads()
        {
            List<Task> listOfTasks = new List<Task>();

            for (var iCntr = 0; iCntr < 20; iCntr++)
            {
                listOfTasks.Add(Task.Run(() =>
                {
                    for (var iMessagesCntr = 0; iMessagesCntr < 10000; iMessagesCntr++)
                    {
                        //Arrange
                        VeryComplexClass testClass = _fixture.Create<VeryComplexClass>();

                        var result = AvroConvert.Serialize(testClass);

                        //Assert
                        Assert.NotNull(result);

                        Thread.Sleep(iCntr);
                    }
                }));
            };

            Task.WaitAll(listOfTasks.ToArray());
        }

Thanks in advance for looking into this
Antonis

**Comment by AdrianStrugala** [comment]
Hello,

Thank you a lot for reporting the problem. I will investigate it and try to fix it soon.

Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Hello,

The bug is resolved. You can find the fix in version 3.2.0 of the AvroConvert.

Regards,
Adrian
