### ISSUE TITLE
3.2.0 Issues with  deserializing enums

### ISSUE THREAD

**Issue by ericsmallwood** [AdrianStrugala/AvroConvert#55]
I am getting the following error when I attempt to deserialize any enum:
![2021-09-14 17_43_12-Error](https://user-images.githubusercontent.com/5509306/133343627-cc37eb7f-356e-4f57-9d02-a6e2150c208f.png)

Here is how I have my model set up: 
![2021-09-14 17_41_07-MktTrConsumer - Microsoft Visual Studio](https://user-images.githubusercontent.com/5509306/133343696-cccfa893-701d-41fe-9476-4c1988aea755.png)

And here is the schema I am using:
![2021-09-14 17_41_48-MktTrConsumer - Microsoft Visual Studio](https://user-images.githubusercontent.com/5509306/133343723-af74b64d-c512-4b9b-9804-d421566c2b4e.png)

I used generate model to create the model from the schema, but for the enum types it created the fields but created no class/enum. How should the enums be represented in the model?

**Comment by AdrianStrugala** [comment]
Good morning,

Thank you for opening the issue. There are two problems I can see here:

**1) Exception in nullable enum deserialization**
I just confirmed that the code is working just fine for the case. Reference [tests](https://github.com/AdrianStrugala/AvroConvert/blob/master/tests/AvroConvertTests/DefaultSerializationDeserialization/EnumTests.cs)

The schema used for deserialization should look like the following:
```
{
   {
      "type":"record",
      "name":"AvroConvertComponentTests.ClassWithEnum",
      "fields":[
         {
            "name":"EnumProp",
            "type":[
               "null",
               {
                  "type":"enum",
                  "name":"AvroConvertComponentTests.TestEnum",
                  "symbols":[
                     "a",
                     "be",
                     "ca",
                     "dlo"
                  ]
               }
            ]
         }
      ]
   }
}
```

Note, yours is not matching the enum name nor values.

**2) Enum is not generated by GenerateModels**
This is an issue on AvroConvert side

Regards,
Adrian

**Comment by ericsmallwood** [comment]
Thanks for the quick reply, I attached the incorrect image for my schema, here is the one I meant to send:
![2021-09-15 10_11_42-MktTrConsumer - Microsoft Visual Studio](https://user-images.githubusercontent.com/5509306/133461667-7dce52b8-a9fd-4083-97df-c35caf607c20.png)

Is there something wrong with the schema still?

I was able to find a work around:
![2021-09-15 10_32_07-MktTrConsumer - Microsoft Visual Studio](https://user-images.githubusercontent.com/5509306/133464024-f1f5de3c-9237-4ce5-99bc-6dfbe04e7db0.png)

**Comment by AdrianStrugala** [comment]
The complete schema should look like this:

```
{
   {
      "type":"record",
      "name":"AvroConvertComponentTests.DefaultSerializationDeserialization.VehicleOrder",
      "fields":[
         {
            "name":"customer_id",
            "type":"int"
         },
         {
            "name":"customer_defined_order_id",
            "type":"string"
         },
         {
            "name":"vehicle_order_requested_epoch_utc_on",
            "type":"long"
         },
         {
            "name":"vehicle_order_requested_local_timezone",
            "type":[
               "null",
               {
                  "type":"enum",
                  "name":"AvroConvertComponentTests.DefaultSerializationDeserialization.vehicle_order_requested_local_timezone_enum",
                  "symbols":[
                     "HAST",
                     "AST",
                     "PST",
                     "MST",
                     "CST",
                     "EST",
                     "NST"
                  ]
               }
            ]
         }
      ]
   }
}
```

I guess, the exception is thrown somewhere else. Both serialization and deserialization worked fine for me on this model. Could you paste here the complete stack trace?

Avro2Json uses the same mechanism under the hood, but it's good that this is working for you

**Comment by AdrianStrugala** [comment]
Hello,

The 2nd problem is resolved. The change is ready in 3.2.1 version of AvroConvert

Thanks,
Adrian
