### ISSUE TITLE
Reading too few records from Avro file

### ISSUE THREAD

**Issue by steinbohrer** [AdrianStrugala/AvroConvert#57]
Hi,

when I try to read the Avro file "userdata1.avro" (see: https://github.com/Teradata/kylo/tree/master/samples/sample-data/avro) with AvroConvert (for example, by using AvroConvert.OpenDeserializer) I only get less than 500 records back.
It was about 468, if I remember correct.
But the file contains exactly 1000 records.
You can check that, for example, with an online Avro reader, like: https://dataformat.net/avro/viewer-and-converter.
Can you confirm this?
Is there a quick fix for this?
I have generated the custom C# class beforehand by using the new "AvroConvert.GenerateModel" method.

Thanks.

**Comment by steinbohrer** [comment]
Ok, found the problem:
The call to "OpenDeserializer" creates a Reader only for the first block of data from the Avro input file.
The file userdata1.avro has 3 blocks of records, each of which is terminated by the 16 sync bytes.
The first block has 468 records, the second 480, and the third has 52 records => 1000 records in total.

Did a quick hack to prove this and I can now iterate over all 1000 records.

**Comment by AdrianStrugala** [comment]
Good morning,

Thank you for opening the issue and investigation. I will try to fix the problem soon.

Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Hello,

The bug is resolved. The fix is ready in 3.2.1 version of AvroConvert

Thanks,
Adrian
