### ISSUE TITLE
Serialising a model which uses an enum causes error

### ISSUE THREAD

**Issue by achomoko** [AdrianStrugala/AvroConvert#7]
Hi 

I get error message "'[GenericEnum] required to write against [Enum] schema but found TestCode.Status" when I serialize a model that uses an enum.

I have had a look at the tests and cannot see an example of how to use a Generic Enum.

**Comment by AdrianStrugala** [comment]
Could you please paste a code sample? It would help me with reproducing the issue.

**Comment by achomoko** [comment]
Sure...

```
    class Program
    {
        static void Main(string[] args)
        {
            var data = new List<Record>()
            {
                new Record() {Name = "Test1", Status = Status.Up},
                new Record() {Name = "Test2", Status = Status.Down}
            };

            byte[] avroObject = AvroConvert.Serialize(data);
        }
    }

    public class Record
    {
        public string Name { get; set;}
        public Status Status { get; set; }
    }
    public enum Status
    {
        Up,
        Down
    }
```

**Comment by AdrianStrugala** [comment]
Thank you for reporting the bug.
The fix is available in v. 2.2.2 of AvroConvert

I will continue working with further integration of Enums.

Regards :)
