### ISSUE TITLE
Generate schema from a c# class with an abstract class as property

### ISSUE THREAD

**Issue by dav1d992** [AdrianStrugala/AvroConvert#72]
My goal is to be able to generate a schema from a c# class that has a dependency on an abstract class. 
When trying to generate a schema from the class the function will throw the exception: `Could not find any matching known type for 'Domain.Animal'`. Do you have any idea how to solve this? 

`Program.cs`: 
```
static void Main(string[] args)
{
     string schema = AvroConvert.GenerateSchema(typeof(Farm));
     Console.WriteLine(schema);
}
```

`Farm.cs`:
```
namespace Domain
{
    public class Farm
    {
        public string Name { get; private set; }
        public List<Animal> Animals{ get; private set; } 
    }
}
```

`Animal.cs` 
```
public abstract class Animal
{
   public boolean isOutside{ get; private set; }
}
```

**Comment by AdrianStrugala** [comment]
Hello,

Thank you for reporting the issue. I will take a look at the case.

Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Hello,

From now on (**version 3.2.5 of AvroConvert**) abstract classes and interfaces are valid members for schema generation. In your case it will produce the following schema:

```csharp
{
   "type":"record",
   "name":"Farm",
   "namespace":"AvroConvertComponentTests.GenerateSchema",
   "fields":[
      {
         "name":"Name",
         "type":"string"
      },
      {
         "name":"Animals",
         "type":{
            "type":"array",
            "items":{
               "type":"record",
               "name":"Animal",
               "namespace":"AvroConvertComponentTests.GenerateSchema",
               "fields":[
                  {
                     "name":"isOutside",
                     "type":"boolean"
                  }
               ]
            }
         }
      }
   ]
}
```

Could I ask you for the use case? I am not sure if the schema based on abstract class will work well with Serialization/Deserialization.

**Comment by dav1d992** [comment]
> From now on (version 3.2.5 of AvroConvert) abstract classes and interfaces are valid members for schema generation

@AdrianStrugala Thanks, I can confirm that it works for abstract classes on v3.2.5 👍👍

> Could I ask you for the use case? I am not sure if the schema based on abstract class will work well with Serialization/Deserialization.

Sure, I'm using the AvroConverter to generate a schema for my `Farm` that contains `Animals`. That schema is then passed to a schema registry which the consumers will be able to pull from. I assume that the consumers can painlessly deserialize as long as they have the schema.
