### ISSUE TITLE
Generate a schema with NO parameterless constructor 

### ISSUE THREAD

**Issue by dav1d992** [AdrianStrugala/AvroConvert#75]
### Objective
Generate a schema from a c# class that has NO parameterless constructor 

### Issue
When trying to generate a schema from the class without a parameterless constructor: ` Type 'Domain.Animal' is not supported by the resolver`. Can we get around this? 

### Details

`Program.cs`: 
```
static void Main(string[] args)
{
     string schema = AvroConvert.GenerateSchema(typeof(Animal));
     Console.WriteLine(schema);
}
```

`Animal.cs`:
```
namespace Domain
{
    public class Animal
    {
        public string Name { get; private set; }

        public Animal(string name)
        {
            Name = name;
        }
    }
}
```

**Comment by AdrianStrugala** [comment]
Hello,
Thanks for reporting this issue. I will take a look.
Regards,
Adrian
