### ISSUE TITLE
EndOfStreamException for file with schema and no data

### ISSUE THREAD

**Issue by glesniakiewicz** [AdrianStrugala/AvroConvert#77]
Hi Adrian,

I have a similar issue as steinbohrer (https://github.com/AdrianStrugala/AvroConvert/issues/59) – getting EndOfStreamException.
It happens when the file contains schema but no data. The code in BaseLineReader constructor -> LoadNextDataBlock() assumes that the items count will always be there, but in my case it is not.
I am not sure if the avro standard requires the block count to be there, but it would be beneficial to handle this scenario just in case it doesn’t.

I fixed it just by adding (BaseLineReader class)

if (_reader.IsReadToEnd())
{
return;
}
At the start of LoadNextDataBlock();

Changed in HasNext()
var hasNext = _lineReaderInternal != null && _lineReaderInternal.HasNext();

Changed in Dispose
_lineReaderInternal?.Dispose();

Similar issue happens with AvroToJson, which can be fixed by adding
if (reader.IsReadToEnd())
{
return result;
}
In Decoder Read method.

Do you mind fixing it in the lib, so I don’t have to use custom changes?

Exp details:

System.IO.EndOfStreamException
  HResult=0x80070026
  Message=Attempted to read past the end of the stream.
  Source=SolTechnology.Avro
  StackTrace:
   at SolTechnology.Avro.AvroObjectServices.Read.Reader.read()
   at SolTechnology.Avro.AvroObjectServices.Read.Reader.ReadLong()
   at SolTechnology.Avro.Features.DeserializeByLine.BaseLineReader`1.LoadNextDataBlock()
   at SolTechnology.Avro.Features.DeserializeByLine.Decoder.OpenReader[T](Stream stream, TypeSchema readSchema)
   at SolTechnology.Avro.AvroConvert.OpenDeserializer[T](Stream stream)

Thanks,
Greg

**Comment by AdrianStrugala** [comment]
Hello,

Thank you for reporting the problem and proposing a fix. I will try to make the required changes soon.

Thanks,
Adrian

**Comment by AdrianStrugala** [comment]
Hello,

Avro files containing header only should now be fully supported (including Deserialization, ByLine, Merge, Avro2Json).
You can test the changes using AvroConvert **v.3.2.7.**

Regards,
Adrian
