### ISSUE TITLE
Unable to deserialize [sample] of schema [Record] to the target type [namespace.sample]

### ISSUE THREAD

**Issue by insighter1** [AdrianStrugala/AvroConvert#90]
**What is the bug?**
Unable to deserialize Avro serialized complex object using deserializeheadless method
The producer application has serialized the object(not with same libraries) and published to Kafka. 
The schema/model file is attached for reference. 

**How to reproduce?**
Please provide steps for reproducing the bug

*What is the Avro schema?*
```The Avro schema is attached for reference. The model class is generated using the avrogen tool and then adapted to be compliant with C#

```

*What is the Avro data? Fill up the section or provide a sample file*
```
[sample.txt](https://github.com/AdrianStrugala/AvroConvert/files/10131138/sample.txt)

```

**What is the expected behavior?**
The expected behavior is to successfully deserialize the data for all complex models as well

**Comment by AdrianStrugala** [comment]
Hello,

Thank you for reporting the problem. For the investigation, I need the data published to Kafka and Avro schema used for deserialization.

Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Closed due to inactivity.
