### ISSUE TITLE
Problem serializing/deserializing arrays

### ISSUE THREAD

**Issue by ombedko** [AdrianStrugala/AvroConvert#92]
### Discussed in https://github.com/AdrianStrugala/AvroConvert/discussions/91

<div type='discussions-op-text'>

<sup>Originally posted by **ombedko** January 26, 2023</sup>
Hi!

First of, thanks for a very cool framework. Suits our purposes exactly.
However, Im having a problem headless serializing an array of custom classes. I would very much prefer to not send the schema along with every message due to the overhead that creates.

With the following data-classes:

```
public class ItemList {
        public Item[] items { get; set; }
}
public class Item {
        public double value { get; set; }
}
```
    
    
If i run the code:
```
var list = new ItemList();
list.items = new Item[1] { new Item() };
list.items[0].value = 3.14;
            
var bytes = AvroConvert.Serialize(list, CodecType.Null);
var deserialized = AvroConvert.Deserialize<ItemList>(bytes);
```

I get the correct result, the desieralized object contains a value = 3.14

However, if I try using the "headless" versoin of serialization:

```
var schema = AvroConvert.GenerateSchema(typeof(ItemList));
var bytes = AvroConvert.SerializeHeadless(list, schema);
var deserialized = AvroConvert.DeserializeHeadless<ItemList>(bytes, schema);
```		

i get a default(double) = 0 as the value out. The bytes array is 10 bytes long with the first byte 2 and rest 0, which indicates that the serialised data contains the value 0 and not 3.14, hence I think the problem is on the serialization side.
            
the "schema" looks correct:
```
{"name":"ItemList","namespace":"LoggingNodeLib.Data.Signals","type":"record","fields":[{"name":"items","type":{"type":"array","items":{"name":"Item","namespace":"LoggingNodeLib.Data.Signals","type":"record","fields":[{"name":"value","type":"double"}]}}}]}
```
 
And it generates the correct class model from https://avroconvertonline.azurewebsites.net/ 

but my desieralized object has the list.items[0].value = 0, and not 3.14 which my original object had.  
Is there some problem with headless seriali<ing arrays of classes within another class?

Next step:

If the Item class contains another cusom class, that property gets default to null which throws a null-object exception on SERIALIZATION (not deserialization), say:
```
public class ItemList {
        public Item[] items { get; set; }
}
public class Dummy { 
        public double value { get; set; } 
}
public class Item {
        public Dummy value { get; set; }
}
```
 
Now running the code:

```
var list = new ItemList();
list.items = new Item[1] { new Item() };
list.items[0].value = new Dummy() { value=3.14};
            
var bytes = AvroConvert.Serialize(list, CodecType.Null);
var deserialized = AvroConvert.Deserialize<ItemList>(bytes);
```

still works, and gives me back an list.items[0].value.value = 3.14

But the headless version throws an exception:
```
var list = new ItemList();
list.items = new Item[1] { new Item() };
list.items[0].value = new Dummy() { value=3.14};
            
var schema = AvroConvert.GenerateSchema(typeof(ItemList));
var bytes = AvroConvert.SerializeHeadless(list, schema);  //null-object Exception thrown here
var deserialized = AvroConvert.DeserializeHeadless<ItemList>(bytes, schema);
```

So, it looks like the SerializeHeadless somehow changes the "list" objects array of Items so that all the Items have default values? Hence, the null object exception on serialisation?

This is my versions setup:
PackageReference Include="Apache.Avro" Version="1.11.1"
PackageReference Include="AvroConvert" Version="3.3.0"
PackageReference Include="DotPulsar" Version="2.5.2"
PackageReference Include="FluentModbus" Version="5.0.0"
PackageReference Include="lib60870.NET" Version="2.2.0"
PackageReference Include="Newtonsoft.Json" Version="13.0.1" 

Thanks again for a very helpfull tool, and for any assistance provided to fix this problem :)
</div>

**Comment by AdrianStrugala** [comment]
Hello,

Thank you for reporting the issue. It indeed looks like a serialization bug, I will try to investigate and resolve it.
Will keep you updated!

Adrian

**Comment by AdrianStrugala** [comment]
Hello @ombedko

The fix is ready. From **v.3.3.1 of AvroConvert** the HeadlessSerialize should properly handle arrays properties of records.

Regards,
Adrian

**Comment by ombedko** [comment]
@AdrianStrugala Thank you very much for the quick fix! I can confirm that it works on my end also, for lists of both nullable and non-nullable types. Much apritiate the help!
