### ISSUE TITLE
Add a non-generic deserialize headless method

### ISSUE THREAD

**Issue by Meyce** [AdrianStrugala/AvroConvert#93]
Could a `DeserializeHeadless` method be created that takes in the type as parameter instead of as a generic argument?  There is a similar method included for `Deserialize`.  I'm dealing with some payloads that have no type/schema information included and I only know there types at runtime.

**Comment by AdrianStrugala** [comment]
Hello,

I think it's possible. Let me check and come back to you.

Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Hello @Meyce,

Your idea has been implemented and it's available from **v.3.3.2 of AvroConvert**.
Thank you for your input.

Regards,
Adrian

**Comment by Meyce** [comment]
Thank you.  Works great.
