### ISSUE TITLE
Error serializing headless from schema with nullable record

### ISSUE THREAD

**Issue by pedrompc** [AdrianStrugala/AvroConvert#94]
I am getting an error trying to serialize an object from a schema which has a nullable record.

Given the following schema, which has a nullable record property Value:
```
var valschema = @"
    {
      ""type"": ""record"",
      ""name"": ""TestObject"",
      ""namespace"": ""ca.dataedu"",
      ""fields"": [
        {
          ""name"": ""Value"",
          ""type"":[
            ""null"",
            {
              ""type"": ""record"",
              ""name"": ""Value"",
              ""fields"": [
                {
                  ""name"": ""KeyNested"",
                  ""type"": ""string""
                },
                {
                  ""name"": ""ValueNested"",
                  ""type"": ""string""
                }
              ]
            }]
        }
      ]
    }
";
```

And the call to SerializeHeadless, using an anonymous object as a parameter (same behaviour using classes):

```
 byte[] value = AvroConvert.SerializeHeadless(new { Value = new { KeyNested = "key1", ValueNested = "val1" } }, valschema);
```

I get the following exception:

```
SolTechnology.Avro.Infrastructure.Exceptions.AvroException: Cannot find a match for <>f__AnonymousType1`2[System.String,System.String] in ["null",{"name":"Value","namespace":"ca.dataedu","type":"record","fields":[{"name":"KeyNested","type":["null","string"],"default":null},{"name":"ValueNested","type":["null","string"],"default":null}]}]
   at SolTechnology.Avro.AvroObjectServices.Write.Resolvers.Union.ResolveUnion(UnionSchema us, TypeSchema[] branchSchemas, Object obj)
   at SolTechnology.Avro.AvroObjectServices.Write.Resolvers.Union.<>c__DisplayClass0_0.<Resolve>b__0(Object v, IWriter e)
   at SolTechnology.Avro.AvroObjectServices.Write.Resolvers.Record.WriteRecordFields(Object recordObj, WriteStep[] writers, IWriter encoder)
   at SolTechnology.Avro.AvroConvert.SerializeHeadless(Object obj, String schema)
```

If I instead remove the nullable record from the schema, it then serializes correctly:
```
var valschema = @"
    {
      ""type"": ""record"",
      ""name"": ""TestObject"",
      ""namespace"": ""ca.dataedu"",
      ""fields"": [
        {
          ""name"": ""Value"",
          ""type"":
            {
              ""type"": ""record"",
              ""name"": ""Value"",
              ""fields"": [
                {
                  ""name"": ""KeyNested"",
                  ""type"": ""string""
                },
                {
                  ""name"": ""ValueNested"",
                  ""type"": ""string""
                }
              ]
            }
        }
      ]
    }
";
```

Is there anything I'm missing with the schema definition? I haven't seen any documentation regarding lack of support for nullable records.

**Comment by AdrianStrugala** [comment]
Hello,

Thank you for reporting the issue. It looks like a bug. I will take some time to investigate.

Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Hello @pedrompc,

The source of the problem was the anonymous object passed as a parameter. Nullable records are handled correctly.
Anyway, the fix for serialization of anonymous objects is available from **v.3.3.2 of AvroConvert**.

Regards,
Adrian

**Comment by pedrompc** [comment]
Hello, thanks very much, the serialization now works with the new version.

However, I have stumbled upon another scenario which doesn't work, which is using an ExpandoObject. Using the same schema as before, but initializing the object like this:

```
 dynamic o = new ExpandoObject();
 o.Value = new { KeyNested = "key1", ValueNested = "val1" };

byte[] value = AvroConvert.SerializeHeadless(o, valschema);
```

The result is a byte with the value 0.

Best regards, and keep up the good work.

**Comment by AdrianStrugala** [comment]
Hello,
ExpandoObject is probably another scenario that I didn't think of. Do you have any other cases?
Regards,
Adrian

**Comment by pedrompc** [comment]
No, so far these are the only two I've come across that didn't work. However, I'll let you know if I run into any other scenario.

Thank you very much

**Comment by AdrianStrugala** [comment]
Support of ExpandoObject for serialization is available from **v.3.3.4 of AvroConvert.**
