### ISSUE TITLE
Error converting from Protobuf-generated class

### ISSUE THREAD

**Issue by malthe** [AdrianStrugala/AvroConvert#95]
**What is the bug?**
I deserialize a Protobuf string to a C# type instance, with code generated by `protoc`:

```csharp
string schemaString = AvroConvert.GenerateSchema(typeof(MyProtobufGeneratedType));
var serialized = AvroConvert.SerializeHeadless(value, schemaString);
```
This raises an exception:
```
System.ArgumentException: Instance property 'Parser' is not defined for type '<Namespace>.MyProtobufGeneratedType' (Parameter 'propertyName')
   at System.Linq.Expressions.Expression.Property(Expression expression, String propertyN…
```
The `Parser` here is a method generated by `protoc` (not an attribute) – and it's not part of the schema (which looks fine):
```csharp
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
public static pb::MessageParser<MyProtobufGeneratedType> Parser { get { return _parser; } }
```
Every Protobuf-generate class has this method.

I get the same issue if I just use `Serialize` where I suppose the schema generation happens implicitly.

**How to reproduce?**
TODO – working on a minimal example, but perhaps someone has a clue what the issue could be.

*What is the Avro schema?*
TODO

*What is the Avro data? Fill up the section or provide a sample file*
TODO

**What is the expected behavior?**
Serialized Avro representation

**Comment by AdrianStrugala** [comment]
Hello,

Thank you for creating the issue. To reproduce it, I need a **schemaString** containing Avro schema and complete **MyProtobufGeneratedType** csharp model. 
The Parser property should be skipped during serialization if it's not a part of the schema.

Regards,
Adrian

**Comment by malthe** [comment]
For example, consider this message:
```protobuf
# test.proto
syntax = "proto3";

package Test;
option csharp_namespace = "<namespace here>";

message Test {
        string type = 1;
        int32 version = 2;
        string correlation_id = 3;
        string operation_id = 4;
        string message_id = 5;
        string timestamp = 6;
}
```

You can generate the .cs-module using `protoc --csharp_out=/tmp test.proto` – I have generated one and [made available as a gist](https://gist.github.com/malthe/944cd32c4437cbc53d7d125abba5ad20).

The Avro schema:
```json
{
  "name": "Test",
  "namespace": "<namespace here>",
  "type": "record",
  "fields": [
    {
      "name": "Type",
      "type": "string"
    },
    {
      "name": "Version",
      "type": "int"
    },
    {
      "name": "CorrelationId",
      "type": "string"
    },
    {
      "name": "OperationId",
      "type": "string"
    },
    {
      "name": "MessageId",
      "type": "string"
    },
    {
      "name": "Timestamp",
      "type": "string"
    }
  ]
}
```

**Comment by AdrianStrugala** [comment]
Thank you for the details. I was able to reproduce the issue locally ([branch](https://github.com/AdrianStrugala/AvroConvert/tree/issue-95))
The problem is that the proto produces 'Parser' and 'Descriptor' **properties** that are not part of the instance type. I will look at the possible solutions, but it may take some time as it is definitely not trivial.

As I am nohow a proto expert, a contribution will be more than welcome :)

**Comment by malthe** [comment]
I'm not an expert either – just a user – but to some extent, a try-statement here could work:

https://github.com/AdrianStrugala/AvroConvert/blob/7c42bc11a4a9bb3f213147a05311839243df75a3/src/AvroConvert/AvroObjectServices/Write/Resolvers/Record.cs#L93

If that throws a `System.ArgumentException` – perhaps it's just a matter of ignoring that, moving on to the next property. But I don't know if there will be trouble further down the road?

**Comment by AdrianStrugala** [comment]
Hello @malthe, 

I have found another solution to the problem. Proto models should now be handled correctly.
The fix is available from **v.3.3.3 of AvroConvert**.
Please let me know if it resolves your issue.

Regards,
Adrian

**Comment by malthe** [comment]
I can confirm that this works. Thanks!
