### ISSUE TITLE
Converting UInt32 value

### ISSUE THREAD

**Issue by malthe** [AdrianStrugala/AvroConvert#96]
**What is the bug?**
My model has a `System.UInt32` value which is declared as `int` in the generated Avro schema.

However, when using `SerializeHeadless`, I get:
```
[Int] required to write against [Int] schema but found System.UInt32
```

To some extent, this makes sense, but what's the solution if you're happy to convert? Ideally, the system should raise an exception if the value does not fit the target type `int`.

**Comment by AdrianStrugala** [comment]
Hello,

The uint32 should be definitely supported. Looks like a bug. I will take care of that.

Regards,
Adrian

**Comment by AdrianStrugala** [comment]
Hello @malthe,

The unsigned number should now be handled correctly. The fix is available from **v.3.3.3 of AvroConvert**.

Regards,
Adrian

**Comment by malthe** [comment]
This seems to work as expected. Thanks!

**Comment by ahzaab** [comment]
I'm getting the same error on 3.4.10
